services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Buepro\Bexio\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/{Model,Validator}'
      - '../Classes/Dto/{Dto}'

  Buepro\Bexio\Controller\AuthController:
    public: true

  Buepro\Bexio\Service\ApiService:
    public: true

  Buepro\Bexio\Task\Invoice\ProcessPayments:
    public: true

  Buepro\Bexio\Task\Invoice\UpdateInvoices:
    public: true

  #
  # Invoice commands
  #
  Buepro\Bexio\Command\Invoice\CreateInvoice:
    tags:
      -
        name: 'console.command'
        command: 'bexio:createinvoice'
        description: 'Create an invoice for a site and a user.'

  Buepro\Bexio\Command\Invoice\ProcessPayments:
    tags:
      - name: 'console.command'
        command: 'bexio:processpayments'
        description: 'Process all invoices that are payed but not processed yet.'

  Buepro\Bexio\Command\Invoice\UpdateInvoices:
    tags:
      -
        name: 'console.command'
        command: 'bexio:updateinvoices'
        description: 'Update local invoices.'

  #
  # Other commands
  #
  Buepro\Bexio\Command\Other\Query:
    tags:
      -
        name: 'console.command'
        command: 'bexio:query'
        description: 'Query an api endpoint and print the result in json format.'

  Buepro\Bexio\Command\Other\Settings:
    tags:
      - name: 'console.command'
        command: 'bexio:settings'
        description: 'Get bexio settings like currencies, bank accounts, languages, payment types, taxes and users.'

  #
  # User commands
  #
  Buepro\Bexio\Command\User\UpdateUsers:
    tags:
      -
        name: 'console.command'
        command: 'bexio:updateusers'
        description: 'Update users with data from bexio contacts.'
