services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Buepro\Bexio\:
    resource: '../Classes/*'

  Buepro\Bexio\Controller\AuthController:
    public: true

  Buepro\Bexio\Service\ApiService:
    public: true

  Buepro\Bexio\Command\UpdateUsers:
    tags:
      -
        name: 'console.command'
        command: 'bexio:updateusers'

  Buepro\Bexio\Command\Query:
    tags:
      -
        name: 'console.command'
        command: 'bexio:query'
