services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Buepro\Bexio\:
    resource: '../Classes/*'

  Buepro\Bexio\Controller\AuthController:
    public: true

  Buepro\Bexio\Service\ApiService:
    public: true

  #
  # Invoice commands
  #
  Buepro\Bexio\Command\Invoice\CreateInvoice:
    tags:
      -
        name: 'console.command'
        command: 'bexio:createinvoice'

  #
  # User commands
  #
  Buepro\Bexio\Command\User\UpdateUsers:
    tags:
      -
        name: 'console.command'
        command: 'bexio:updateusers'

  #
  # Other commands
  #
  Buepro\Bexio\Command\Other\Query:
    tags:
      -
        name: 'console.command'
        command: 'bexio:query'

  Buepro\Bexio\Command\Other\Settings:
    tags:
      - name: 'console.command'
        command: 'bexio:settings'
